In [51]:
# Import pandas for data manipulation
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

In [52]:
# Read the CSV file
df = pd.read_csv(r'../dataset/mymoviedb.csv', engine='python', on_bad_lines='skip', encoding='utf-8')

In [53]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [54]:
df.shape

(9837, 9)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9837 non-null   object
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   object
 5   Vote_Average       9827 non-null   object
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: float64(1), object(8)
memory usage: 691.8+ KB

In [56]:
# Convert to numeric, coerce errors to NaN
df['Vote_Average'] = pd.to_numeric(df['Vote_Average'], errors='coerce')

# Also convert Vote_Count while we're at it
df['Vote_Count'] = pd.to_numeric(df['Vote_Count'], errors='coerce')

In [57]:
df.isnull().sum()

Release_Date          0
Title                 9
Overview              9
Popularity           10
Vote_Count           11
Vote_Average         11
Original_Language    10
Genre                11
Poster_Url           11
dtype: int64

In [58]:
df.dropna(inplace=True)

In [59]:
df.isnull().sum()

Release_Date         0
Title                0
Overview             0
Popularity           0
Vote_Count           0
Vote_Average         0
Original_Language    0
Genre                0
Poster_Url           0
dtype: int64

In [60]:
#df["Overview"] = df["Overview"].fillna("")

In [61]:
# ==========================================
# Remove Duplicate Records
# ==========================================

print("Before :", df.shape)

df.drop_duplicates(inplace=True)

print("After :", df.shape)

Before : (9826, 9)
After : (9826, 9)

In [62]:
df["Release_Date"] = pd.to_datetime(
    df["Release_Date"],
    errors="coerce"
)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9826 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9826 non-null   datetime64[ns]
 1   Title              9826 non-null   object
 2   Overview           9826 non-null   object
 3   Popularity         9826 non-null   float64
 4   Vote_Count         9826 non-null   float64
 5   Vote_Average       9826 non-null   float64
 6   Original_Language  9826 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 767.7+ KB

In [64]:
df["Year"] = df["Release_Date"].dt.year

In [65]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url,Year
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940.0,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...,2021
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151.0,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...,2022
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122.0,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...,2022
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076.0,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...,2021
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793.0,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...,2021

In [66]:
df["Genre"] = df["Genre"].str.lower()

df["Overview"] = df["Overview"].str.lower()

df["Original_Language"] = df["Original_Language"].str.lower()

In [67]:
df["Genre"] = df["Genre"].str.strip()

df["Overview"] = df["Overview"].str.strip()

df["Original_Language"] = df["Original_Language"].str.strip()

In [68]:
df["Tags"] = (
    df["Genre"] + " " +
    df["Overview"] + " " +
    df["Original_Language"]
)

In [69]:
df["Tags"] = df["Tags"].str.replace(r"\s+", " ", regex=True)

In [70]:
df[["Title","Tags"]].head()

                     Title                                               Tags
0  Spider-Man: No Way Home  action, adventure, science fiction peter parke...
1               The Batman  crime, mystery, thriller in his second year of...
2                  No Exit  thriller stranded at a rest stop in the mounta...
3                  Encanto  animation, comedy, family, fantasy the tale of...
4           The King's Man  action, adventure, thriller, war as a collecti...

In [71]:
# ==========================================
# Final Dataset for Recommendation System
# ==========================================

movies = df[
    [
        "Title",
        "Tags",
        "Genre",
        "Overview",
        "Original_Language",
        "Popularity",
        "Vote_Average",
        "Vote_Count",
        "Poster_Url",
        "Year"
    ]
].copy()

In [72]:
movies.head()

,Title,Tags,Genre,Overview,Original_Language,Popularity,Vote_Average,Vote_Count,Poster_Url,Year
0,Spider-Man: No Way Home,"action, adventure, science fiction peter parke...","action, adventure, science fiction",peter parker is unmasked and no longer able to...,en,5083.954,8.3,8940.0,https://image.tmdb.org/t/p/original/1g0dhYtq4i...,2021
1,The Batman,"crime, mystery, thriller in his second year of...","crime, mystery, thriller","in his second year of fighting crime, batman u...",en,3827.658,8.1,1151.0,https://image.tmdb.org/t/p/original/74xTEgt7R3...,2022
2,No Exit,thriller stranded at a rest stop in the mounta...,thriller,stranded at a rest stop in the mountains durin...,en,2618.087,6.3,122.0,https://image.tmdb.org/t/p/original/vDHsLnOWKl...,2022
3,Encanto,"animation, comedy, family, fantasy the tale of...","animation, comedy, family, fantasy","the tale of an extraordinary family, the madri...",en,2402.201,7.7,5076.0,https://image.tmdb.org/t/p/original/4j0PNHkMr5...,2021
4,The King's Man,"action, adventure, thriller, war as a collecti...","action, adventure, thriller, war",as a collection of history's worst tyrants and...,en,1895.511,7.0,1793.0,https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...,2021

In [73]:
print(movies.shape)

(9826, 10)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9826 entries, 0 to 9836
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9826 non-null   datetime64[ns]
 1   Title              9826 non-null   object
 2   Overview           9826 non-null   object
 3   Popularity         9826 non-null   float64
 4   Vote_Count         9826 non-null   float64
 5   Vote_Average       9826 non-null   float64
 6   Original_Language  9826 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
 9   Year               9826 non-null   int32
 10  Tags               9826 non-null   object
dtypes: datetime64[ns](1), float64(3), int32(1), object(6)
memory usage: 882.8+ KB

In [75]:
movies.to_csv(
    "../dataset/clean_movies.csv",
    index=False
)